/**
 * Drop du lundi: 5 picks for the coming 7 days, with a "why" each.
 * Members: generated lazily on the first visit of the Paris week
 * (parisWeekStart), stored in weekly_drops so it stays stable all week.
 * Anonymous visitors: generic picks (quality + popularity), optionally
 * personalised with signals from localStorage (not stored).
 */
import 'server-only'
import { and, eq } from 'drizzle-orm'
import { db, weeklyDrops } from '@sortir/db'
import { effectiveEnd, parisWeekStart } from '@/lib/paris-time'
import { explainPick, getPersonalPicks, getPersonalQuery, type PersonalSignals } from '@/lib/recommendations'
import { getCardsByIds } from './member'
import type { CardEvent } from '@/lib/events/types'

export const DROP_SIZE = 5

export interface WeeklyDrop {
  weekStart: string
  events: CardEvent[]
  /** Picks of this drop that are already over (stored drops only). */
  ended: number
  personalized: boolean
  archetype: string | null
  /** True when generated by this request. */
  isNew: boolean
  error: boolean
}

export async function getAnonymousDrop(signals: PersonalSignals = {}): Promise<WeeklyDrop> {
  const picks = await getPersonalPicks({ userId: null, signals, when: 'week', limit: DROP_SIZE })
  return {
    weekStart: parisWeekStart(),
    events: picks.events,
    ended: 0,
    personalized: picks.plan.personalized,
    archetype: picks.plan.archetype,
    isNew: false,
    error: picks.error,
  }
}

export async function getMemberDrop(userId: string): Promise<WeeklyDrop> {
  const weekStart = parisWeekStart()
  const where = and(eq(weeklyDrops.userId, userId), eq(weeklyDrops.weekStart, weekStart))
  const [stored] = await db.select({ ids: weeklyDrops.eventIds }).from(weeklyDrops).where(where).limit(1)

  if (stored) {
    const ids = stored.ids.split(',').filter(Boolean)
    const [cards, plan] = await Promise.all([getCardsByIds(ids), getPersonalQuery(userId)])
    const now = new Date()
    const live = cards.filter((e) => effectiveEnd(e) >= now)
    return {
      weekStart,
      events: live.map((e) => ({ ...e, reason: explainPick(e, plan) })),
      ended: cards.length - live.length,
      personalized: plan.personalized,
      archetype: plan.archetype,
      isNew: false,
      error: false,
    }
  }

  const picks = await getPersonalPicks({ userId, when: 'week', limit: DROP_SIZE })
  if (picks.events.length) {
    await db
      .insert(weeklyDrops)
      .values({ userId, weekStart, eventIds: picks.events.map((e) => e.id).join(',') })
      .onConflictDoNothing()
  }
  return {
    weekStart,
    events: picks.events,
    ended: 0,
    personalized: picks.plan.personalized,
    archetype: picks.plan.archetype,
    isNew: picks.events.length > 0,
    error: picks.error,
  }
}
